//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturuldu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elektronik_saglik_platformu_web_doktor
{


    public partial class SiteMaster
    {

        /// <summary>
        /// HeadContent denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// MainContent denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
